"""auroincrement was aadded into stations

Revision ID: 31eac6c65ccc
Revises: 90af828db3b1
Create Date: 2018-05-02 09:12:32.947853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31eac6c65ccc'
down_revision = '90af828db3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
