"""Added driver table, added routes

Revision ID: 86914cdb5ca1
Revises: ac69a2fa4fec
Create Date: 2018-03-12 19:41:37.986715

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '86914cdb5ca1'
down_revision = 'ac69a2fa4fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'drivers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=32), nullable=False),
        sa.Column('last_name', sa.String(length=32), nullable=False),
        sa.Column('middle_name', sa.String(length=32), nullable=False),
        sa.Column('experience', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(
        'route_stations', 'route_id',
        existing_type=sa.VARCHAR(length=8),
        nullable=False
    )
    op.alter_column(
        'route_stations', 'station_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.add_column(
        'routes',
        sa.Column(
            'backward_direction',
            geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING'),
            nullable=True
        )
    )
    op.add_column(
        'routes',
        sa.Column(
            'forward_direction',
            geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING'),
            nullable=True
        )
    )
    op.drop_index('idx_stations_coord', table_name='stations')
    op.add_column(
        'transports',
        sa.Column('driver_id', sa.Integer(), nullable=False)
    )
    op.drop_index('idx_transports_position', table_name='transports')
    op.create_foreign_key(None, 'transports', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transports', type_='foreignkey')
    op.create_index('idx_transports_position', 'transports', ['position'],
                    unique=False)
    op.drop_column('transports', 'driver_id')
    op.create_index('idx_stations_coord', 'stations', ['coord'], unique=False)
    op.drop_column('routes', 'forward_direction')
    op.drop_column('routes', 'backward_direction')
    op.alter_column('route_stations', 'station_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('route_stations', 'route_id',
                    existing_type=sa.VARCHAR(length=8),
                    nullable=True)
    op.drop_table('drivers')
    # ### end Alembic commands ###
