"""auroincrement was aadded into stations

Revision ID: 90af828db3b1
Revises: afe2ab214b42
Create Date: 2018-05-02 08:46:09.188515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90af828db3b1'
down_revision = 'afe2ab214b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
