"""Updated schema

Revision ID: ac69a2fa4fec
Revises: 
Create Date: 2018-03-12 19:06:37.179215

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ac69a2fa4fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis;')
    op.execute('CREATE EXTENSION IF NOT EXISTS  postgis_topology;')
    op.create_table(
        'routes',
        sa.Column('id', sa.String(length=8), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'stations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=512), nullable=False),
        sa.Column('coord', geoalchemy2.types.Geometry(
            geometry_type='POINT'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'route_stations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('route_id', sa.String(length=8), nullable=True),
        sa.Column('station_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
        sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'transports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('route_id', sa.String(length=8), nullable=False),
        sa.Column('position', geoalchemy2.types.Geometry(
            geometry_type='POINT'), nullable=True),
        sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transports')
    op.drop_table('route_stations')
    op.drop_table('stations')
    op.drop_table('routes')
    op.execute('DROP EXTENSION IF EXISTS postgis CASCADE;')
    op.execute('DROP EXTENSION IF EXISTS postgis_topology CASCADE;')
    # ### end Alembic commands ###
