"""geo type was added

Revision ID: afe2ab214b42
Revises: cb05c6bd7b5a
Create Date: 2018-05-02 06:55:12.904357

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe2ab214b42'
down_revision = 'cb05c6bd7b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('backward_direction', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True))
    op.add_column('routes', sa.Column('forward_direction', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'forward_direction')
    op.drop_column('routes', 'backward_direction')
    # ### end Alembic commands ###
