"""geo params were changed

Revision ID: cb05c6bd7b5a
Revises: 7738e911fe2e
Create Date: 2018-05-02 06:52:34.157101

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb05c6bd7b5a'
down_revision = '7738e911fe2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'backward_direction')
    op.drop_column('routes', 'forward_direction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'routes',
        sa.Column(
            'backward_direction',
            geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING'),
            nullable=True
        )
    )
    op.add_column(
        'routes',
        sa.Column(
            'forward_direction',
            geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING'),
            nullable=True
        )
    )
    # ### end Alembic commands ###
